### ISSUE TITLE
Authentication model (cookie/token-based)

### ISSUE THREAD

**Issue by arsenykonohovwork** [arsenykonohovwork/inspectah-curvaceous#10]
Follow tutorial:
https://www.youtube.com/playlist?list=PLSpJkDDmpFZ7GowbJE-mvX09zY9zfYatI

Make some documentation;

# Authentication model

![authentication model](https://user-images.githubusercontent.com/8690043/45958901-44787980-c021-11e8-869f-9e554f6014fd.PNG)

You can find it [here](https://drive.google.com/file/d/1f555sywv_LuOzRKsrS5PO1-T5VnLbjgA/view?usp=sharing)

## Cookie-based authentication
It can be devided into the steps:

1. If the user doesn't have an account he must sign up. The client posts a HTTP request to the server containing his username and password. 

2. The server receives this request and hashes the password before storing the username and the password in the database. This allows not to see users' actual passwords if someone gains access to the database.

3. After signing up the user must log in. He provides his username and password and this is posted as a HTTP request to the server.

4. The server looks up the username in the database, hashes the supplied login password, and compares it to the previously hashed password in the database. If the request is valid it will create a session by using the user information fetched from the database and store them. For each session a unique id called session Id is created. By default a session Id will be given to the client through the browser. If it doesn't check out access the access can be denied by sending a 401 status code and ending the request.

5. Browser will submit this session Id on each subsequent requests. The session ID is verified against in the database. Based on this session id website will identify which client the session is belonging to and then the request is giving the access.

6. When a client logs out the session is destroyed both client-side and server-side.

## Token-based authentication
Unlike of cookies tokens are stateless. The server doesn’t keep a record of the session. Every action will be accompanied by a unique token that the server verifies one at a time.

Steps to create token-based authentication:

1. The user enters his username and password, and the server verifies that the information is correct. Each token is signed with an encrypted key code or digital signature that only the server will know. The server verifies a token by running the algorithm that created the signature. If the two match the server knows that the token is valid.

2. When the server finds a match a signed token is sent and stored in the user’s local storage. The token is encoded and signed just like a handwritten signature. If the signature hasn’t been tampered with the server knows the token came from an authentic source and validates the request.

3. To complete an authentication the token is attached to the user’s request. The server then decodes and verifies the token. The website’s server verifies the token without storing information by checking that the token’s encrypted signature matches its security algorithm. A match allows the user to log in.

4. When the user logs out the token is destroyed.

**Comment by iScous** [comment]
@arsenykonohovwork ready for review
