### ISSUE TITLE
Space for documentations;

### ISSUE THREAD

**Issue by arsenykonohovwork** [arsenykonohovwork/inspectah-curvaceous#17]
@iScous We have to gather all documentations that are result of spikes and the rest of issues in one place;

### The list of documents for the application

1. [Application concept](https://github.com/arsenykonohovwork/inspectah-curvaceous/blob/enhancement/17-Space-for-documentations/docs/Application%20concept.md)
2. [Business logic model](https://github.com/arsenykonohovwork/inspectah-curvaceous/blob/enhancement/17-Space-for-documentations/docs/Aplication%20concept.PNG)
3. [Set up environment](https://github.com/arsenykonohovwork/inspectah-curvaceous/blob/enhancement/17-Space-for-documentations/docs/Set%20up%20environment.md)
4. [Set up database for the project](https://github.com/arsenykonohovwork/inspectah-curvaceous/blob/enhancement/17-Space-for-documentations/docs/Set%20up%20database%20for%20project.md)
5. [Authentication model](https://github.com/arsenykonohovwork/inspectah-curvaceous/blob/enhancement/17-Space-for-documentations/docs/Authentication%20model.md)

**Comment by iScous** [comment]
@arsenykonohovwork ready for review
