### ISSUE TITLE
Investigate how to Create Templates for new Issue and PR;

### ISSUE THREAD

**Issue by arsenykonohovwork** [arsenykonohovwork/inspectah-curvaceous#23]
# How to create Pull Request Template

It's quite easy to generate a PR template for your project. Create a file named PULL_REQUEST_TEMPLATE and place it one of three locations:

The root of your project
.github folder
docs folder
An extension is optional, but Markdown (.md) is supported. I've chosen to create a Markdown template so you can utilize features like Markdown formatting, @-mentions, and task lists.

Once GitHub detects the PULL_REQUEST_TEMPLATE file, it will auto-populate new PRs with the contents.

# How to create Issue Template

1. On GitHub, navigate to the main page of the repository.

2. Under your repository name, click  Settings.

3. In the "Features" section, under "Issues," click Start template setup.

4. Use the Add template drop-down menu, and click on the type of template you'd like to create.
5. To preview or edit the template before committing it to the repository, click Preview and edit.
6. To edit the template, click , and type in the fields to edit their contents.
7. When you're finished editing and previewing your template, click Propose changes in the upper right corner of the page.
8. Enter a commit message describing your changes.
9. Below the commit message fields, decide whether to commit your template directly to the default branch, or to create a new branch and open a pull request. For more information about pull requests, see "About pull requests."
10. Click Commit changes. Once these changes are merged into the default branch, the template will be available for contributors to use when they open new issues in the repository.

**Comment by VladislavGulik** [comment]
@arsenykonohovwork, I'm done with work with doc for templates and created PR #28.
