### ISSUE TITLE
Set up environment

### ISSUE THREAD

**Issue by arsenykonohovwork** [arsenykonohovwork/inspectah-curvaceous#9]
## Environment

- [x] Set up Docker container;
- [x] Node.js & NPM (use latest LTS);
- [x] PostgressQl;
- [x] Express;

Docker: version 18.06.1-ce-win73;
Node.js: version 8.12.0;
NPM: version 6.4.1;
PostgreSQL: version 10.5

# Set up environment

While perfoming this issue i have investigated the following things:

  - What is the docker
  - What is a docker file and its creation
  - How to create a docker image including node.js, npm, express.js, handlebars.js, pug and sequelize into it

  It was very helpful for me to use the article about how to create docker file, docker image and push it to the docker hub from this link. https://buddy.works/guides/how-dockerize-node-application

  Steps that i followed to complete this issue are:

  * Installed docker from the offical site
  * Created a docker file with the correct instructions. It includes a package.json file with all the dependencies needed to install correctly node.js, npm and frameworks
  * Created a docker image from the docker file
  * Builded the docker image
  * Pushed the docker image to the docker hub
  
To build a docker image from a dockerfile we need to use the following command:
```sh
$ docker build -t <image name> .
```

To run docker container:
```sh
$ docker run -p <port:port> <image name>
```

To deploy an image to the docker hub:
```sh
$ docker build -t [USERNAME]/<image name> .
$ docker login
$ docker push [USERNAME]/<image name>
```

To enable to navigate in docker container while it's running the package.json was modified with the following string in scripts section:
```sh
"start": "http-server ./app -p 8080 -c-1"
```

To specify multiple containers we can use docker-compose.yml file. To create and start containers it's possible to use the command:
```sh
docker-compose up -d
```

**Comment by iScous** [comment]
@arsenykonohovwork ready for review
